package tfg;
// Generated 25-jul-2018 12:22:30 by Hibernate Tools 4.3.1



/**
 * CaballosduenosId generated by hbm2java
 */
public class CaballosduenosId  implements java.io.Serializable {


     private int caballo;
     private String dueno;

    public CaballosduenosId() {
    }

    public CaballosduenosId(int caballo, String dueno) {
       this.caballo = caballo;
       this.dueno = dueno;
    }
   
    public int getCaballo() {
        return this.caballo;
    }
    
    public void setCaballo(int caballo) {
        this.caballo = caballo;
    }
    public String getDueno() {
        return this.dueno;
    }
    
    public void setDueno(String dueno) {
        this.dueno = dueno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CaballosduenosId) ) return false;
		 CaballosduenosId castOther = ( CaballosduenosId ) other; 
         
		 return (this.getCaballo()==castOther.getCaballo())
 && ( (this.getDueno()==castOther.getDueno()) || ( this.getDueno()!=null && castOther.getDueno()!=null && this.getDueno().equals(castOther.getDueno()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCaballo();
         result = 37 * result + ( getDueno() == null ? 0 : this.getDueno().hashCode() );
         return result;
   }   


}


