package tfg;
// Generated 25-jul-2018 12:22:30 by Hibernate Tools 4.3.1



/**
 * Caballosduenos generated by hbm2java
 */
public class Caballosduenos  implements java.io.Serializable {


     private CaballosduenosId id;

    public Caballosduenos() {
    }

    public Caballosduenos(CaballosduenosId id) {
       this.id = id;
    }
   
    public CaballosduenosId getId() {
        return this.id;
    }
    
    public void setId(CaballosduenosId id) {
        this.id = id;
    }




}


