package tfg;
// Generated 25-jul-2018 12:22:30 by Hibernate Tools 4.3.1



/**
 * Caballos generated by hbm2java
 */
public class Caballos  implements java.io.Serializable {


     private int cod;
     private String nombre;
     private String raza;
     private String venta;
     private int cuadra;
     private int montura;
     private int embocadura;
     private int altura;
     private String herraje;
     private String tratamientoVeterinario;
     private String alquiler;
     private String imagen;

    public Caballos() {
    }

    public Caballos(int cod, String nombre, String raza, String venta, int cuadra, int montura, int embocadura, int altura, String herraje, String tratamientoVeterinario, String alquiler, String imagen) {
       this.cod = cod;
       this.nombre = nombre;
       this.raza = raza;
       this.venta = venta;
       this.cuadra = cuadra;
       this.montura = montura;
       this.embocadura = embocadura;
       this.altura = altura;
       this.herraje = herraje;
       this.tratamientoVeterinario = tratamientoVeterinario;
       this.alquiler = alquiler;
       this.imagen = imagen;
    }
   
    public int getCod() {
        return this.cod;
    }
    
    public void setCod(int cod) {
        this.cod = cod;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getRaza() {
        return this.raza;
    }
    
    public void setRaza(String raza) {
        this.raza = raza;
    }
    public String getVenta() {
        return this.venta;
    }
    
    public void setVenta(String venta) {
        this.venta = venta;
    }
    public int getCuadra() {
        return this.cuadra;
    }
    
    public void setCuadra(int cuadra) {
        this.cuadra = cuadra;
    }
    public int getMontura() {
        return this.montura;
    }
    
    public void setMontura(int montura) {
        this.montura = montura;
    }
    public int getEmbocadura() {
        return this.embocadura;
    }
    
    public void setEmbocadura(int embocadura) {
        this.embocadura = embocadura;
    }
    public int getAltura() {
        return this.altura;
    }
    
    public void setAltura(int altura) {
        this.altura = altura;
    }
    public String getHerraje() {
        return this.herraje;
    }
    
    public void setHerraje(String herraje) {
        this.herraje = herraje;
    }
    public String getTratamientoVeterinario() {
        return this.tratamientoVeterinario;
    }
    
    public void setTratamientoVeterinario(String tratamientoVeterinario) {
        this.tratamientoVeterinario = tratamientoVeterinario;
    }
    public String getAlquiler() {
        return this.alquiler;
    }
    
    public void setAlquiler(String alquiler) {
        this.alquiler = alquiler;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }




}


