package tfg;
// Generated 25-jul-2018 12:22:30 by Hibernate Tools 4.3.1



/**
 * Clases generated by hbm2java
 */
public class Clases  implements java.io.Serializable {


     private ClasesId id;
     private String disciplina;
     private int pista;
     private String profesor;

    public Clases() {
    }

    public Clases(ClasesId id, String disciplina, int pista, String profesor) {
       this.id = id;
       this.disciplina = disciplina;
       this.pista = pista;
       this.profesor = profesor;
    }
   
    public ClasesId getId() {
        return this.id;
    }
    
    public void setId(ClasesId id) {
        this.id = id;
    }
    public String getDisciplina() {
        return this.disciplina;
    }
    
    public void setDisciplina(String disciplina) {
        this.disciplina = disciplina;
    }
    public int getPista() {
        return this.pista;
    }
    
    public void setPista(int pista) {
        this.pista = pista;
    }
    public String getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(String profesor) {
        this.profesor = profesor;
    }




}


