package tfg;
// Generated 25-jul-2018 12:22:30 by Hibernate Tools 4.3.1



/**
 * ClasesclientesId generated by hbm2java
 */
public class ClasesclientesId  implements java.io.Serializable {


     private String diaSemana;
     private String hora;
     private String asistente;
     private int codigo;

    public ClasesclientesId() {
    }

    public ClasesclientesId(String diaSemana, String hora, String asistente, int codigo) {
       this.diaSemana = diaSemana;
       this.hora = hora;
       this.asistente = asistente;
       this.codigo = codigo;
    }
   
    public String getDiaSemana() {
        return this.diaSemana;
    }
    
    public void setDiaSemana(String diaSemana) {
        this.diaSemana = diaSemana;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }
    public String getAsistente() {
        return this.asistente;
    }
    
    public void setAsistente(String asistente) {
        this.asistente = asistente;
    }
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClasesclientesId) ) return false;
		 ClasesclientesId castOther = ( ClasesclientesId ) other; 
         
		 return ( (this.getDiaSemana()==castOther.getDiaSemana()) || ( this.getDiaSemana()!=null && castOther.getDiaSemana()!=null && this.getDiaSemana().equals(castOther.getDiaSemana()) ) )
 && ( (this.getHora()==castOther.getHora()) || ( this.getHora()!=null && castOther.getHora()!=null && this.getHora().equals(castOther.getHora()) ) )
 && ( (this.getAsistente()==castOther.getAsistente()) || ( this.getAsistente()!=null && castOther.getAsistente()!=null && this.getAsistente().equals(castOther.getAsistente()) ) )
 && (this.getCodigo()==castOther.getCodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDiaSemana() == null ? 0 : this.getDiaSemana().hashCode() );
         result = 37 * result + ( getHora() == null ? 0 : this.getHora().hashCode() );
         result = 37 * result + ( getAsistente() == null ? 0 : this.getAsistente().hashCode() );
         result = 37 * result + this.getCodigo();
         return result;
   }   


}


