package tfg;
// Generated 25-jul-2018 12:22:30 by Hibernate Tools 4.3.1



/**
 * Clasesclientes generated by hbm2java
 */
public class Clasesclientes  implements java.io.Serializable {


     private ClasesclientesId id;

    public Clasesclientes() {
    }

    public Clasesclientes(ClasesclientesId id) {
       this.id = id;
    }
   
    public ClasesclientesId getId() {
        return this.id;
    }
    
    public void setId(ClasesclientesId id) {
        this.id = id;
    }




}


