package tfg;
// Generated 25-jul-2018 12:22:30 by Hibernate Tools 4.3.1



/**
 * Cuadras generated by hbm2java
 */
public class Cuadras  implements java.io.Serializable {


     private int numero;
     private String limpio;
     private String comida;

    public Cuadras() {
    }

    public Cuadras(int numero, String limpio, String comida) {
       this.numero = numero;
       this.limpio = limpio;
       this.comida = comida;
    }
   
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public String getLimpio() {
        return this.limpio;
    }
    
    public void setLimpio(String limpio) {
        this.limpio = limpio;
    }
    public String getComida() {
        return this.comida;
    }
    
    public void setComida(String comida) {
        this.comida = comida;
    }




}


