package tfg;
// Generated 25-jul-2018 12:22:30 by Hibernate Tools 4.3.1



/**
 * Embocaduras generated by hbm2java
 */
public class Embocaduras  implements java.io.Serializable {


     private int cod;
     private String tipoEmbocadura;
     private String tipoFilete;
     private String tipoBocado;

    public Embocaduras() {
    }

	
    public Embocaduras(int cod, String tipoEmbocadura) {
        this.cod = cod;
        this.tipoEmbocadura = tipoEmbocadura;
    }
    public Embocaduras(int cod, String tipoEmbocadura, String tipoFilete, String tipoBocado) {
       this.cod = cod;
       this.tipoEmbocadura = tipoEmbocadura;
       this.tipoFilete = tipoFilete;
       this.tipoBocado = tipoBocado;
    }
   
    public int getCod() {
        return this.cod;
    }
    
    public void setCod(int cod) {
        this.cod = cod;
    }
    public String getTipoEmbocadura() {
        return this.tipoEmbocadura;
    }
    
    public void setTipoEmbocadura(String tipoEmbocadura) {
        this.tipoEmbocadura = tipoEmbocadura;
    }
    public String getTipoFilete() {
        return this.tipoFilete;
    }
    
    public void setTipoFilete(String tipoFilete) {
        this.tipoFilete = tipoFilete;
    }
    public String getTipoBocado() {
        return this.tipoBocado;
    }
    
    public void setTipoBocado(String tipoBocado) {
        this.tipoBocado = tipoBocado;
    }




}


