package tfg;
// Generated 25-jul-2018 12:22:30 by Hibernate Tools 4.3.1



/**
 * Empresas generated by hbm2java
 */
public class Empresas  implements java.io.Serializable {


     private int cod;
     private String nombre;
     private String direccion;
     private Integer codigoPostal;
     private String ciudad;
     private String tipoEmpresa;
     private int telefono;

    public Empresas() {
    }

	
    public Empresas(int cod, String nombre, String direccion, int telefono) {
        this.cod = cod;
        this.nombre = nombre;
        this.direccion = direccion;
        this.telefono = telefono;
    }
    public Empresas(int cod, String nombre, String direccion, Integer codigoPostal, String ciudad, String tipoEmpresa, int telefono) {
       this.cod = cod;
       this.nombre = nombre;
       this.direccion = direccion;
       this.codigoPostal = codigoPostal;
       this.ciudad = ciudad;
       this.tipoEmpresa = tipoEmpresa;
       this.telefono = telefono;
    }
   
    public int getCod() {
        return this.cod;
    }
    
    public void setCod(int cod) {
        this.cod = cod;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(Integer codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getTipoEmpresa() {
        return this.tipoEmpresa;
    }
    
    public void setTipoEmpresa(String tipoEmpresa) {
        this.tipoEmpresa = tipoEmpresa;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }




}


