package tfg;
// Generated 25-jul-2018 12:22:30 by Hibernate Tools 4.3.1



/**
 * Pistas generated by hbm2java
 */
public class Pistas  implements java.io.Serializable {


     private int numero;
     private String suelo;
     private String imagen;

    public Pistas() {
    }

    public Pistas(int numero, String suelo, String imagen) {
       this.numero = numero;
       this.suelo = suelo;
       this.imagen = imagen;
    }
   
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public String getSuelo() {
        return this.suelo;
    }
    
    public void setSuelo(String suelo) {
        this.suelo = suelo;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }




}


