package tfg;
// Generated 25-jul-2018 12:22:30 by Hibernate Tools 4.3.1



/**
 * ReservascaballosId generated by hbm2java
 */
public class ReservascaballosId  implements java.io.Serializable {


     private String horasReserva;
     private int caballo;
     private String cliente;
     private String fecha;

    public ReservascaballosId() {
    }

    public ReservascaballosId(String horasReserva, int caballo, String cliente, String fecha) {
       this.horasReserva = horasReserva;
       this.caballo = caballo;
       this.cliente = cliente;
       this.fecha = fecha;
    }
   
    public String getHorasReserva() {
        return this.horasReserva;
    }
    
    public void setHorasReserva(String horasReserva) {
        this.horasReserva = horasReserva;
    }
    public int getCaballo() {
        return this.caballo;
    }
    
    public void setCaballo(int caballo) {
        this.caballo = caballo;
    }
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReservascaballosId) ) return false;
		 ReservascaballosId castOther = ( ReservascaballosId ) other; 
         
		 return ( (this.getHorasReserva()==castOther.getHorasReserva()) || ( this.getHorasReserva()!=null && castOther.getHorasReserva()!=null && this.getHorasReserva().equals(castOther.getHorasReserva()) ) )
 && (this.getCaballo()==castOther.getCaballo())
 && ( (this.getCliente()==castOther.getCliente()) || ( this.getCliente()!=null && castOther.getCliente()!=null && this.getCliente().equals(castOther.getCliente()) ) )
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getHorasReserva() == null ? 0 : this.getHorasReserva().hashCode() );
         result = 37 * result + this.getCaballo();
         result = 37 * result + ( getCliente() == null ? 0 : this.getCliente().hashCode() );
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         return result;
   }   


}


