package tfg;
// Generated 25-jul-2018 12:22:30 by Hibernate Tools 4.3.1



/**
 * ReservasserviciosId generated by hbm2java
 */
public class ReservasserviciosId  implements java.io.Serializable {


     private int servicio;
     private String cliente;
     private String fecha;

    public ReservasserviciosId() {
    }

    public ReservasserviciosId(int servicio, String cliente, String fecha) {
       this.servicio = servicio;
       this.cliente = cliente;
       this.fecha = fecha;
    }
   
    public int getServicio() {
        return this.servicio;
    }
    
    public void setServicio(int servicio) {
        this.servicio = servicio;
    }
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReservasserviciosId) ) return false;
		 ReservasserviciosId castOther = ( ReservasserviciosId ) other; 
         
		 return (this.getServicio()==castOther.getServicio())
 && ( (this.getCliente()==castOther.getCliente()) || ( this.getCliente()!=null && castOther.getCliente()!=null && this.getCliente().equals(castOther.getCliente()) ) )
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getServicio();
         result = 37 * result + ( getCliente() == null ? 0 : this.getCliente().hashCode() );
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         return result;
   }   


}


