package tfg;
// Generated 25-jul-2018 12:22:30 by Hibernate Tools 4.3.1



/**
 * Reservascaballos generated by hbm2java
 */
public class Reservascaballos  implements java.io.Serializable {


     private ReservascaballosId id;

    public Reservascaballos() {
    }

    public Reservascaballos(ReservascaballosId id) {
       this.id = id;
    }
   
    public ReservascaballosId getId() {
        return this.id;
    }
    
    public void setId(ReservascaballosId id) {
        this.id = id;
    }




}


