package tfg;
// Generated 25-jul-2018 12:22:30 by Hibernate Tools 4.3.1



/**
 * ReservaspistasId generated by hbm2java
 */
public class ReservaspistasId  implements java.io.Serializable {


     private int pista;
     private String cliente;
     private String fecha;
     private String horasReserva;

    public ReservaspistasId() {
    }

    public ReservaspistasId(int pista, String cliente, String fecha, String horasReserva) {
       this.pista = pista;
       this.cliente = cliente;
       this.fecha = fecha;
       this.horasReserva = horasReserva;
    }
   
    public int getPista() {
        return this.pista;
    }
    
    public void setPista(int pista) {
        this.pista = pista;
    }
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getHorasReserva() {
        return this.horasReserva;
    }
    
    public void setHorasReserva(String horasReserva) {
        this.horasReserva = horasReserva;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReservaspistasId) ) return false;
		 ReservaspistasId castOther = ( ReservaspistasId ) other; 
         
		 return (this.getPista()==castOther.getPista())
 && ( (this.getCliente()==castOther.getCliente()) || ( this.getCliente()!=null && castOther.getCliente()!=null && this.getCliente().equals(castOther.getCliente()) ) )
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) )
 && ( (this.getHorasReserva()==castOther.getHorasReserva()) || ( this.getHorasReserva()!=null && castOther.getHorasReserva()!=null && this.getHorasReserva().equals(castOther.getHorasReserva()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPista();
         result = 37 * result + ( getCliente() == null ? 0 : this.getCliente().hashCode() );
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         result = 37 * result + ( getHorasReserva() == null ? 0 : this.getHorasReserva().hashCode() );
         return result;
   }   


}


