package tfg;
// Generated 25-jul-2018 12:22:30 by Hibernate Tools 4.3.1



/**
 * Reservaspistas generated by hbm2java
 */
public class Reservaspistas  implements java.io.Serializable {


     private ReservaspistasId id;

    public Reservaspistas() {
    }

    public Reservaspistas(ReservaspistasId id) {
       this.id = id;
    }
   
    public ReservaspistasId getId() {
        return this.id;
    }
    
    public void setId(ReservaspistasId id) {
        this.id = id;
    }




}


