package tfg;
// Generated 25-jul-2018 12:22:30 by Hibernate Tools 4.3.1



/**
 * Reservasservicios generated by hbm2java
 */
public class Reservasservicios  implements java.io.Serializable {


     private ReservasserviciosId id;

    public Reservasservicios() {
    }

    public Reservasservicios(ReservasserviciosId id) {
       this.id = id;
    }
   
    public ReservasserviciosId getId() {
        return this.id;
    }
    
    public void setId(ReservasserviciosId id) {
        this.id = id;
    }




}


