package tfg;
// Generated 25-jul-2018 12:22:30 by Hibernate Tools 4.3.1



/**
 * Servicios generated by hbm2java
 */
public class Servicios  implements java.io.Serializable {


     private int cod;
     private String nombre;
     private String dias;
     private int precio;

    public Servicios() {
    }

    public Servicios(int cod, String nombre, String dias, int precio) {
       this.cod = cod;
       this.nombre = nombre;
       this.dias = dias;
       this.precio = precio;
    }
   
    public int getCod() {
        return this.cod;
    }
    
    public void setCod(int cod) {
        this.cod = cod;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDias() {
        return this.dias;
    }
    
    public void setDias(String dias) {
        this.dias = dias;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }




}


