package tfg;
// Generated 25-jul-2018 12:22:30 by Hibernate Tools 4.3.1



/**
 * Trabajadores generated by hbm2java
 */
public class Trabajadores  implements java.io.Serializable {


     private String dni;
     private String nombre;
     private String direccion;
     private Integer codPostal;
     private String ciudad;
     private String tipoTrabajador;
     private int salario;
     private int telefono;
     private String imagen;

    public Trabajadores() {
    }

	
    public Trabajadores(String dni, String nombre, String direccion, String tipoTrabajador, int salario, int telefono, String imagen) {
        this.dni = dni;
        this.nombre = nombre;
        this.direccion = direccion;
        this.tipoTrabajador = tipoTrabajador;
        this.salario = salario;
        this.telefono = telefono;
        this.imagen = imagen;
    }
    public Trabajadores(String dni, String nombre, String direccion, Integer codPostal, String ciudad, String tipoTrabajador, int salario, int telefono, String imagen) {
       this.dni = dni;
       this.nombre = nombre;
       this.direccion = direccion;
       this.codPostal = codPostal;
       this.ciudad = ciudad;
       this.tipoTrabajador = tipoTrabajador;
       this.salario = salario;
       this.telefono = telefono;
       this.imagen = imagen;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getCodPostal() {
        return this.codPostal;
    }
    
    public void setCodPostal(Integer codPostal) {
        this.codPostal = codPostal;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getTipoTrabajador() {
        return this.tipoTrabajador;
    }
    
    public void setTipoTrabajador(String tipoTrabajador) {
        this.tipoTrabajador = tipoTrabajador;
    }
    public int getSalario() {
        return this.salario;
    }
    
    public void setSalario(int salario) {
        this.salario = salario;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }




}


