package tfg;
// Generated 25-jul-2018 12:22:30 by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private UsuariosId id;
     private String nombre;
     private String direccion;
     private int codPostal;
     private String ciudad;
     private int telefono;
     private String sexo;
     private int admin;

    public Usuarios() {
    }

    public Usuarios(UsuariosId id, String nombre, String direccion, int codPostal, String ciudad, int telefono, String sexo, int admin) {
       this.id = id;
       this.nombre = nombre;
       this.direccion = direccion;
       this.codPostal = codPostal;
       this.ciudad = ciudad;
       this.telefono = telefono;
       this.sexo = sexo;
       this.admin = admin;
    }
   
    public UsuariosId getId() {
        return this.id;
    }
    
    public void setId(UsuariosId id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getCodPostal() {
        return this.codPostal;
    }
    
    public void setCodPostal(int codPostal) {
        this.codPostal = codPostal;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public int getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(int admin) {
        this.admin = admin;
    }




}


